; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Apr 14 2022 21:25:25 GMT+0200 (CEST)
; Wait for set temperatures to be reached
M116 P0

